CREATE TABLE TestClass1 (
id INT NOT NULL GENERATED ALWAYS AS IDENTITY,
string1 VARCHAR(255),
decimal1 DECIMAL(14,2),
date1 TIMESTAMP,
boolean1 BOOLEAN,
PRIMARY KEY (id)
);

CREATE TABLE TestClass2 (
class2Id BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
stringData VARCHAR(255),
decimalField DECIMAL(14,2),
PRIMARY KEY (class2Id)
);